name: Run tests on push


on:
  push:
    branches:
    - develop

jobs:
  run_tests_job:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
          ref: develop
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: App - Restore dependencies
      run: dotnet restore ./ApiProject/calcalc.sln
    - name: Clean the solution
      run: dotnet clean ./ApiProject/calcalc.sln
    - name: Show
      run: cat ./TestProject/tests/UnitFoodItemList.cs
    - name: App - Build
      run: dotnet build ./ApiProject/calcalc.sln --no-restore --configuration Release
    - name: Show number of tests
      run: dotnet test ./TestProject/tests/tests.csproj --list-tests --verbosity=quiet --nologo | wc -l
    - name: Test - Run tests
      run: dotnet test ./TestProject/tests/tests.csproj --logger "trx;LogFileName=TestResults.trx"
    - name: Upload test result
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ./TestProject/tests/TestResults/TestResults.trx
  revert-change:
    runs-on: ubuntu-latest
    needs: [ run_tests_job ]  # we need to say the job that sometimes fails is a dependency
    if: ${{ failure() }}      # because if it fails
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # check out the current and prior state
      - name: "Revert the commit that triggered this run, then push it to main"
        shell: bash
        run: |
          echo "Reverting ${{ github.sha }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git revert --no-edit ${{ github.sha }}
          git push origin develop

